/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class matrix_math */

#ifndef _Included_matrix_math
#define _Included_matrix_math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     matrix_math
 * Method:    quickInverseSqrt
 * Signature: ()V
 */
JNIEXPORT jfloat JNICALL Java_matrix_math_quickInverseSqrt
  (JNIEnv *, jobject thisObject, jfloat number);

#ifdef __cplusplus
}
#endif
#endif